### ISSUE TITLE
Environment problem

### ISSUE THREAD

**Issue by He-Yichen** [liuqidong07/LEADER-pytorch#1]
Could you please tell me your Python version? I tried to reproduce your code as described in the paper using Python 3.6.5. However, when I run 'pip install -r requirements.txt', I encounter numerous version errors, such as: 'ERROR: Could not find a version that satisfies the requirement accelerate==0.18.0'.

**Comment by liuqidong07** [comment]
Hello,

Thanks for your interest in our work. Sorry for the misspecification of the python version. Actually, the python version is 3.9.5 and you can try it. I will fix the error in the next version of the paper.

Best regards

**Comment by He-Yichen** [comment]
> Hello,
> 
> Thanks for your interest in our work. Sorry for the misspecification of the python version. Actually, the python version is 3.9.5 and you can try it. I will fix the error in the next version of the paper.
> 
> Best regards

Thank you！I have another question. There is a code in the construction.ipynb file: "atc2drug = pd.read_csv("./auxiliary/WHO ATC-DDD 2021-12-03.csv")". How can I obtain the file "WHO ATC-DDD 2021-12-03.csv"?
@liuqidong07

**Comment by liuqidong07** [comment]
> > Hello,
> > Thanks for your interest in our work. Sorry for the misspecification of the python version. Actually, the python version is 3.9.5 and you can try it. I will fix the error in the next version of the paper.
> > Best regards
> 
> Thank you！I have another question. There is a code in the construction.ipynb file: "atc2drug = pd.read_csv("./auxiliary/WHO ATC-DDD 2021-12-03.csv")". How can I obtain the file "WHO ATC-DDD 2021-12-03.csv"? @liuqidong07

Hello, I acquire the file from this link https://github.com/fabkury/atcd. Thanks for your reminder, and I will update the readme.
