### ISSUE TITLE
Questions about dataset format.

### ISSUE THREAD

**Issue by guosyjlu** [liuqidong07/LEADER-pytorch#11]
Hi,

Thanks for your great work! I have some questions about the dataset used in this paper. 

1. Does the dataset in this paper format as below?

**Question:** Template filled with realistic data as shown in 
>The patient has <VISIT NUM> times ICU visits. In the 1 visit, the patient had diagnosis: \<DIAG NAME\>, ..., \<DIAG NAME\>; procedures: \<PROC NAME\>, ..., <PROC NAME>; The patient was prescribed drugs: \<MED NAME\>, ..., \<MED NAME\>. In the 2 visit, .... In this visit, the patient has diagnosis: \<DIAG NAME\>, ..., \<DIAG NAME\>; procedures: \<PROC NAME\>, ..., \<PROC NAME\>. Then, the patient should be prescribed:

**Answer**: The ground-truth list of medicine

2. How to obtain the dataset with the format above? Do I need to download the full data of MIMIC-IV (~9GB) to achieve this?

**Comment by liuqidong07** [comment]
Hello, thanks for your interest in our work.
1. Yes, the template is the format you mentioned. The detailed prompt construction can be found in `data/mimic4/construction.ipynb`.
2. You may follow the 2nd step of the instruction in README. As for the raw data, we only use the `prescriptions.csv`, `diagnoses_icd.csv` and `procedures_icd.csv`.

Best,

**Comment by guosyjlu** [comment]
Thanks for your prompt response.
