### ISSUE TITLE
安装环境的一些疑问？

### ISSUE THREAD

**Issue by ricartojason** [liuqidong07/LEADER-pytorch#12]
您好，我想请问下您的环境使用的python版本是3.6.5吗？按照论文的说法我在安装requirments的依赖时，出现了多个依赖版本错误，是不是更新了python版本呢？此外我看meta官方已经停止使用llama_7B了，那目前使用llama2可以吗？最后想请教下数据集具体使用到了那些文件呢/

**Comment by liuqidong07** [comment]
您好，我们实际使用的是Python3.9.5，arXiv论文中的版本有误，可以参见下面这个issue：
https://github.com/liuqidong07/LEADER-pytorch/issues/1#issuecomment-1982296019

针对您的第二个问题，我认为我们的代码直接适配LLaMA2是可以的，可以自行尝试。

用到数据集中的具体文件在预处理的代码中有写，并没有修改名称，可以参考预处理代码`construction.ipynb`

祝好，

**Comment by ricartojason** [comment]
好的，感谢您的回复！
