### ISSUE TITLE
dataset process in construction.ipynb

### ISSUE THREAD

**Issue by chensaics** [liuqidong07/LEADER-pytorch#3]
Hi Liu, Nice work.
May I know how you got these files :
./auxiliary/RXCUI2atc4.csv
./auxiliary/drug-atc.csv
./auxiliary/ndc2RXCUI.txt
./auxiliary/drugbank_drugs_info.csv
./auxiliary/drug-DDI.csv

**Comment by liuqidong07** [comment]
Hello,
Thanks for your interest in our work. These files can be obtained from the SafeDrug repo (https://github.com/sjy1203/GAMENet/tree/master/data). 
Thanks for your reminder. I will update this information to README.

Best regards,
Qidong

**Comment by chensaics** [comment]
Thank you for your guide.
The drugbank_drugs_info.csv is lost in that project.
Is it from the drugbank website ([drugbank](https://go.drugbank.com/releases/latest#full))?

**Comment by liuqidong07** [comment]
Hello, 
I obtain this file from this link (https://drive.google.com/file/d/1EzIlVeiIR6LFtrBnhzAth4fJt6H_ljxk/view). You can refer to the repo of SafeDrug (https://github.com/ycq091044/SafeDrug) for more related information.

Best regards,
Qidong

**Comment by chensaics** [comment]
Thank you so much
