### ISSUE TITLE
Topk filtering for Diagnosis or Procedures

### ISSUE THREAD

**Issue by liyifo** [liuqidong07/LEADER-pytorch#6]
Hello, in data processing, you have filtered out diagnoses or procedures except for the top k, but have the drugs corresponding to the filtered diagnoses not been filtered out. Is there a problem with the processed data?

**Comment by liuqidong07** [comment]
Hello, thanks for your interest in our work. Actually, we refer to the preprocessing code of GAMENet and SafeDrug. Could you please refer to the specific code in our repo?
Best,

**Comment by liyifo** [comment]
> Hello, thanks for your interest in our work. Actually, we refer to the preprocessing code of GAMENet and SafeDrug. Could you please refer to the specific code in our repo? Best,

Thank you for your reply. Here is the code I am referring to:
SafeDrug/data/processing.py  line 162 `diag_pd = filter_2000_most_diag(diag_pd)`

**Comment by liuqidong07** [comment]
Hello. In my view, this line will filter out redundant medication, diagnoses, and procedures. 
https://github.com/liuqidong07/LEADER-pytorch/blob/75bac886bfce983b0fe6b8856e53f1abb13a436a/data/mimic3/utils.py#L236
You can check this function. 
Best,
