### ISSUE TITLE
requirement环境问题

### ISSUE THREAD

**Issue by 815382636** [liuqidong07/LEADER-pytorch#7]
trl==0.7.6要求transformers>4.31.0，两个包该用什么版本?

**Comment by 815382636** [comment]
![image](https://github.com/user-attachments/assets/fee4a819-6391-423d-b781-e0744c88df45)

**Comment by liuqidong07** [comment]
您好，感谢对我们工作的关注。我们的代码中实际没有用到trl，所以transformers请使用4.28.1。
祝好
