### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by swordqiqi** [liuqidong07/LEADER-pytorch#8]
您好，非常好的工作！
我想复现您的实验，但是数据需要经过授权才能获得，请问还有其他获得数据的方式么？

**Comment by liuqidong07** [comment]
您好，感谢对我们工作的关注。非常抱歉，我认为唯一的方式是通过授权获取数据，因为这些医疗数据涉及到伦理问题。我记得获取授权并不困难，只需要通过一个课程的学习，以及提交一份申请。祝好

**Comment by swordqiqi** [comment]
好的，谢谢您！但我现在遇到了另外一个问题在distill_trainer.py文件中，从LEADER中导入了PNet，但LEADER.py中我没找到PNnet

**Comment by liuqidong07** [comment]
#9
