### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by swordqiqi** [liuqidong07/LEADER-pytorch#9]
您好，非常好的工作！
在阅读您的代码时，我遇到了一个问题，就是在distill_trainer.py文件中，从LEADER中导入了PNet，但LEADER.py中我没找到PNnet。

**Comment by liuqidong07** [comment]
抱歉，前段时间很忙，回复晚了！很感谢您对我们工作的关注。这里是package名称导入错误了，将PNet改为LEADER即可。我已经将改后的代码传上来了，您也可以重新拉取一下。
感谢，祝好！
